---
- hosts: localhost

  collections: 
    - community.kubernetes
  
  tasks:
    - name: GET WORKER NODE DETAILS
      community.kubernetes.k8s_info:
        kind: Node
        namespace: default

    - name: Add Bitnami's chart repository.
      community.kubernetes.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Install phpMyAdmin with Helm.
      community.kubernetes.helm:
        name: phpmyadmin
        chart_ref: bitnami/phpmyadmin
        release_namespace: default
        values:
          service:
            type: NodePort
